#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from "fs"
import { execSync } from "child_process"

console.log("🎨 Обновляю README релизами с демо...")

const changelog = readFileSync("CHANGELOG.md", "utf8")
let readme = readFileSync("README.md", "utf8")

// Парсим changelog - ТОЛЬКО версии с демо
const versionBlocks = changelog.split("## v").slice(1)
let prettyChangelog = "## 📋 История версий\n\n"
const processedVersions = new Set()

versionBlocks.forEach((versionBlock) => {
    const versionMatch = versionBlock.match(/^(\d+\.\d+\.\d+)/)
    if (!versionMatch) return

    const version = `v${versionMatch[1]}`
    if (processedVersions.has(version)) return
    processedVersions.add(version)

    // ПРОВЕРЯЕМ ДЕМО - если нет демо, пропускаем
    const hasDemo = existsSync(`docs/${version}.gif`) || existsSync(`docs/${version}.png`)
    if (!hasDemo) {
        console.log(`⏭️ Пропускаем ${version} - нет демо`)
        return
    }

    // Пропускаем если нет фич
    if (!versionBlock.includes("### ✨ Фичи")) {
        console.log(`⏭️ Пропускаем ${version} - нет фич`)
        return
    }

    // Извлекаем фичи
    const features = []
    const lines = versionBlock.split("\n")
    let inFeaturesSection = false

    for (const line of lines) {
        if (line.includes("### ✨ Фичи")) {
            inFeaturesSection = true
            continue
        }
        if (inFeaturesSection && line.includes("### ")) break
        if (inFeaturesSection && line.trim().startsWith("-") && features.length < 3) {
            const cleanFeature = line
                .replace(/^- /, "")
                .replace(/\(\[#\d+\]\([^)]+\)\)/g, "")
                .replace(/\[#\d+\]\([^)]+\)/g, "")
                .replace(/#\d+\s*/, "")
                .replace(/\[[^\]]+\]\([^)]+\)/g, "")
                .trim()

            if (cleanFeature && !cleanFeature.toLowerCase().includes("тест") && cleanFeature.length > 10) {
                features.push(cleanFeature)
            }
        }
    }

    if (features.length === 0) return

    console.log(`✅ Добавляем ${version} - есть демо и ${features.length} фич`)

    // Форматируем версию
    prettyChangelog += `### 🟢 ${version}\n\n`

    // Добавляем демо (гарантированно есть)
    if (existsSync(`docs/${version}.gif`)) {
        prettyChangelog += `**Демо работы**  \n<img src="docs/${version}.gif" width="400" />\n\n`
    } else {
        prettyChangelog += `**Демо работы**  \n<img src="docs/${version}.png" width="400" />\n\n`
    }

    // Добавляем функционал
    prettyChangelog += `**Функционал:**\n`
    features.forEach((feature) => {
        prettyChangelog += `- ${feature}\n`
    })

    prettyChangelog += `\n**Релиз:** https://github.com/ione-chebkn/js-calculator/releases/tag/${version}\n\n---\n\n`
})

// Заменяем секцию между маркерами
if (readme.includes("<!-- AUTOGENERATED_SECTION START -->")) {
    const startMarker = "<!-- AUTOGENERATED_SECTION START -->"
    const endMarker = "<!-- AUTOGENERATED_SECTION END -->"

    const startIndex = readme.indexOf(startMarker)
    const endIndex = readme.indexOf(endMarker, startIndex + startMarker.length)

    if (startIndex !== -1 && endIndex !== -1) {
        readme =
            readme.substring(0, startIndex + startMarker.length) + "\n" + prettyChangelog + readme.substring(endIndex)
        console.log("✅ Секция обновлена")
    }
} else {
    console.log("❌ Маркер <!-- AUTOGENERATED_SECTION START --> не найден")
    process.exit(1)
}

// Сохраняем
writeFileSync("README.md", readme)
console.log("✅ README обновлён с релизами, у которых есть демо!")
try {
    execSync("git add README.md", { stdio: "inherit" })
    execSync('git commit -m "docs: update README with demo releases"', { stdio: "inherit" })
    execSync("git push", { stdio: "inherit" })
    console.log("🚀 Изменения запущены!")
} catch (error) {
    console.log("💡 README обновлён локально")
}
